id: PDD498288
initial_creation_type: ocr
source_metadata:
  volumes:
    5ddc5747a0884e3491f072a997564889:
      base_file: v003.txt
      image_group_id: I1PD95848
      title: རྒྱུད་ཀྱི་རྒྱལ་པོ་ཆེན་པོ་དཔལ་དགྱེས་པའི་རྡོ་རྗེའི་དཀའ་འགྲེལ་སྤྱན་འབྱེད།
      total_pages: 1687
      volume_number: 3
